### ISSUE TITLE
Contrast-agnostic model on a lumbar SCI patient outputs incorrect segmentation

### ISSUE THREAD

**Issue by naga-karthik** [sct-pipeline/contrast-agnostic-softseg-spinalcord#118]
@valosekj tried the `contrast-agnostic` v2.4 model on a lumbar SCI patient from the `sci-zurich` dataset. The model even segmented regions outside the cord. 

**RESULTS FROM contrast-agnostic model (version: 2.4)**

<details><summary>Segmentation outside of the cord:</summary>

<img width="1473" alt="image" src="https://github.com/user-attachments/assets/73255bee-bad1-49e9-a8f2-a85d771718e9">

</details>

<details><summary>Undersegmented cord at the level of the lesion:</summary>

red - lesion
blue - cord

Issue: the cord should cover also the region at and below the lesion

<img width="1473" alt="image" src="https://github.com/user-attachments/assets/4719bb38-ef4b-46d1-a591-4f9474dc8815">

</details>

**Comment by naga-karthik** [comment]
Even though the these [datasets](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/v2.4/datasplits) were used for training (including SCI and lumbar datasets), I think that the subject above is a corner case (i.e. lumbar SCI with metal hardware) and is quite difficult to segment given that we don't have that many lumbar scans and scans with hardware (compared to healthy and MS subjects). 

Therefore, one possible option I recommend is to consider also using the `SCIseg` model for cord segmentation. 

**Reason**: It is difficult for one model to be able to reliably segment any cord, given the heterogeneity in the scans, resolutions and image quality. So, if a user has a challenging test case (like the one @valosekj had), we could ask the user to also consider trying `SCIseg` model if the `contrast-agnostic` model doesn't work well. The specialist model might be better at such extreme cases than the generalist model that works reasonably well on any/all contrasts.

**Comment by jcohenadad** [comment]
@naga-karthik do you think we should consider adding this dataset in the contrast-agnostic model? if it makes the model more "agnostic" to pathologies, then it's a big plus for that model. Ultimately, the more cases it can cover, the more it will be used (and cited).

**Comment by naga-karthik** [comment]
hey @jcohenadad, are you referring to a particular dataset? Maybe I'm missing something, [here](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/v2.4/datasplits) are the datasets currently included in the model training.

**Comment by valosekj** [comment]
> hey @jcohenadad, are you referring to a particular dataset? Maybe I'm missing something, [here](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/tree/v2.4/datasplits) are the datasets currently included in the model training.

Thanks for the clarification, Naga! I probably introduced some confusion here during yesterday's meeting, as I thought that _only_ SCIsegV2 included the `sci-zurich` dataset for training. And I did not realize that contrast-agnostic was actually also trained on this dataset.

**Comment by naga-karthik** [comment]
[IMPORTANT] hey @valosekj, I made a mistake! Turns out that SCI datasets were **not** included in the contrast-agnostic v2.4 version. For reference, here's a summary of what datasets were included!

<details> 

<summary> Datasets used in v2.4 </summary>

### Datasets used (n=7):

* `datasplit_basel-mp2rage_seed50.json`
* `datasplit_canproco_seed50.json`
* `datasplit_data-multi-subject_seed50.json`
* `datasplit_dcm-zurich_seed50.json`
* `datasplit_lumbar-epfl_seed50.json`
* `datasplit_lumbar-vanderbilt_seed50.json`
* `datasplit_sct-testing-large_seed50.json`


### Training/Validation/Test splits across all datasets:

* Number of training samples (i.e. images, not subjects): 2700
* Number of validation samples (i.e. images, not subjects): 503
* Number of testing samples (i.e. images, not subjects): 616


### Training/Validation/Test across each contrast (n=9):

| Contrast   |   #train_images |   #validation_images |   #test_images |
|:-----------|----------------:|---------------------:|---------------:|
| dwi        |             172 |                   38 |             49 |
| mt-off     |             158 |                   36 |             49 |
| mt-on      |             168 |                   37 |             49 |
| psir       |             217 |                   49 |             67 |
| stir       |              56 |                   15 |             18 |
| t1w        |             197 |                   40 |             54 |
| t2star     |             633 |                   87 |            106 |
| t2w        |            1018 |                  190 |            213 |
| unit1      |              81 |                   11 |             11 |
| TOTAL      |            2700 |                  503 |            616 |


### Model name for internal/dev purposes:
```
nnunet_seed=50_ndata=7_ncont=9_pad=zero_nf=32_opt=adam_lr=0.001_AdapW_bs=2_20240425-170840
```

</details>

I was losing track of what datasets were being added in each release so I create a summary like the one above and upload it with every release. They can found in `datasplits.md` if you manually download the release folder. Turns out this was indeed the saviour! :)

That said, the current un-released version of the model is trained on all SCI datasets and the DCM datasets. Would you like to try it out internally on the same subject (linked in my 1st comment) ?

**Comment by naga-karthik** [comment]
I went ahead and tested the latest model on the same subject. The issue is only partly resolved. With the latest model, we don't get any segmentations outside the SC (as reported in the original issue) but the model is still unable to segment the cord at the site of the implant. 

I tested the model on T1w and ax_T2w images as well. The model does slightly better on T1w (at least we see some prediction after the implant) for ax_T2w it works perfectly fine! I know that this does not resolve the issue as far as computing `sct_analyze_lesion` is concerned. Do you think we can have a workaround based on these additional segmentations? (namely, the axial)

<detalils> 
<summary> sag T2w pred </summary>

![ezgif com-animated-gif-maker](https://github.com/user-attachments/assets/4ef414be-d48d-44f4-a862-2d21bae024dd)

</details>

<detalils> 
<summary> sag T1w pred </summary>

![ezgif com-animated-gif-maker-2](https://github.com/user-attachments/assets/c353c4a5-d6a9-4ae7-994b-b05b20de376c)

</details>

**Comment by naga-karthik** [comment]
I found something interesting, thank to @valosekj ! My testing [script](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/main/monai/run_inference_single_image.py#L364-L365) by default had the keep-largest-component enabled. As a result, we lost some prediction after the metal implant. 

When I re-tested by keeping everything, we have a better prediction now. (and there are still no predictions outside the cord)

<details>

<summary> disabling keep-largest-component </summary>

![ezgif com-animated-gif-maker-3](https://github.com/user-attachments/assets/cef8b566-d193-4ce2-a5cf-9f9c85f8eaa0)

yellow: prediction with the largest component
blue: prediction without the largest component (i.e. keep everything). note that blue is overlaid on yellow i.e. we still have the complete segmentation for blue as well (just that it's hidden behind yellow)

</details> 

@valosekj I think you can maybe try it on a few other subjects? Please keep in mind the [train/test split used for sci-zurich](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/nk/contrast-agnostic-v2/datasplits/datasplit_sci-zurich_seed50.yaml). You might see a difference in performance if you're running it on the entire dataset depending on which subjects were included in training/testing.

**Comment by jcohenadad** [comment]
> I was losing track of what datasets were being added in each release so I create a summary like the one above and upload it with every release. They can found in datasplits.md if you manually download the release folder.

@naga-karthik this shows the importance of creating a script that automatically fetches the dataset and generate a log listing the data used to produce the release. How can everyone be sure that the manually created file `datasplits.md` has no error? As requested in the old issue #15, it becomes increasingly urgent to perform training in a transparent and reproducible way. The training script should generate the list of training dataset (not you manually) and package that list alongside the generated model, that is ultimately uploaded on github release. Thank you.

**Comment by naga-karthik** [comment]
oops, sorry for the misunderstanding! I am _not_ doing this manually! it's automatically output from [this function](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/nk/contrast-agnostic-v2/monai/utils.py#L55) when I start the training and the output is stored in the results folder (which is simply uploaded to the GH release) :)

**Comment by valosekj** [comment]
Thanks for digging in, @naga-karthik!

> @valosekj I think you can maybe try it on a few other subjects?

Sure! Do you think it would be possible to zip the v2.5 model and make a pre-release? By doing so, I could easily reuse [my existing bash script](https://github.com/ivadomed/model_seg_sci/blob/813caae549a6eb4bfd69b392ee53129f304e6a9e/midsagittal_measures/01_compute_midsagittal_lesion_length_and_width.sh#L121-L125) just by adding `sct_deepseg -custom-url <URL_TO_V2.5>`.

**Comment by naga-karthik** [comment]
@valosekj can I close this issue?

**Comment by valosekj** [comment]
> @valosekj can I close this issue?

Sorry, Naga, I have not tested the updated model yet. Maybe we can close the issue, and I will test the new version (https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/pull/125), which is about to be released.

**Comment by valosekj** [comment]
# Testing different contrast-agnostic versions

Follow up on https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/118#issue-2542414988

Subject: `sub-zh04_ses-02_acq-sag_T2w.nii.gz` from `sci-zurich`

## Updating my local SCT

PR: https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4695

```
cd $SCT_DIR
git fetch
git checkout nk/update-contrast-agnostic-model
```

## r20240531 (v2.4)

I wanted to reproduce segmentations from https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/issues/118#issue-2542414988, so trying r20240531 (v2.4).

Release r20240531: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.4

```
sct_deepseg -install seg_sc_contrast_agnostic -custom-url https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.4/model_soft_bin_20240425-170840.zip
```

```
cd ~/data/data.neuro.polymtl.ca/sci-zurich/sub-zh04/ses-02/anat
git annex get sub-zh04_ses-02_acq-sag_T2w.nii.gz

sct_deepseg -i sub-zh04_ses-02_acq-sag_T2w.nii.gz -task seg_sc_contrast_agnostic

...

Using custom model from URL 'https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.4/model_soft_bin_20240425-170840.zip'.
...
```

Getting error... 

<details><summary>Full error:</summary>

```
$ sct_deepseg -i sub-zh04_ses-02_acq-sag_T2w.nii.gz -task seg_sc_contrast_agnostic

--
Spinal Cord Toolbox (git-nk/update-contrast-agnostic-model-fb5decc95ca58e5295a4739e336f95eb007c3f93)

sct_deepseg -i sub-zh04_ses-02_acq-sag_T2w.nii.gz -task seg_sc_contrast_agnostic
--


#######################################################################
Please cite the following paper when using the contrast-agnostic model:

Bédard*, S., Karthik*, E.N., Tsagkas, C., Pravatà, E., Granziera, C., Smith, A.C., Weber, K.A., & Cohen-Adad, J. (2023).
Towards contrast-agnostic soft segmentation of the spinal cord. ArXiv, abs/2310.15402. https://arxiv.org/abs/2310.15402
#######################################################################

Using custom model from URL 'https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.4/model_soft_bin_20240425-170840.zip'.
Traceback (most recent call last):
  File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_deepseg.py", line 407, in <module>
    main(sys.argv[1:])
  File "/Users/valosek/code/sct_latest/spinalcordtoolbox/scripts/sct_deepseg.py", line 316, in main
    im_lst, target_lst = inference.segment_non_ivadomed(path_model, model_type, input_filenames, thr,
  File "/Users/valosek/code/sct_latest/spinalcordtoolbox/deepseg/inference.py", line 121, in segment_non_ivadomed
    net = create_net(path_model, device)
  File "/Users/valosek/code/sct_latest/spinalcordtoolbox/deepseg/monai.py", line 130, in create_nnunet_from_plans
    model.load_state_dict(checkpoint)
  File "/Users/valosek/code/sct_latest/python/envs/venv_sct/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PlainConvUNet:
	size mismatch for encoder.stages.4.0.convs.0.conv.weight: copying a param with shape torch.Size([320, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 256, 3, 3, 3]).
	size mismatch for encoder.stages.4.0.convs.0.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.0.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.0.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.0.all_modules.0.weight: copying a param with shape torch.Size([320, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 256, 3, 3, 3]).
	size mismatch for encoder.stages.4.0.convs.0.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.0.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.0.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.1.conv.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for encoder.stages.4.0.convs.1.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.1.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.1.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.1.all_modules.0.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for encoder.stages.4.0.convs.1.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.1.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.4.0.convs.1.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.0.conv.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for encoder.stages.5.0.convs.0.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.0.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.0.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.0.all_modules.0.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for encoder.stages.5.0.convs.0.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.0.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.0.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.1.conv.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for encoder.stages.5.0.convs.1.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.1.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.1.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.1.all_modules.0.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for encoder.stages.5.0.convs.1.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.1.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for encoder.stages.5.0.convs.1.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.conv.weight: copying a param with shape torch.Size([320, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 256, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.all_modules.0.weight: copying a param with shape torch.Size([320, 256, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 256, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.0.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.conv.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.all_modules.0.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.4.0.convs.1.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.conv.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.all_modules.0.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.0.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.conv.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.all_modules.0.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.encoder.stages.5.0.convs.1.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.0.conv.weight: copying a param with shape torch.Size([320, 640, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 768, 3, 3, 3]).
	size mismatch for decoder.stages.0.convs.0.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.0.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.0.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.0.all_modules.0.weight: copying a param with shape torch.Size([320, 640, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 768, 3, 3, 3]).
	size mismatch for decoder.stages.0.convs.0.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.0.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.0.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.1.conv.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.stages.0.convs.1.conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.1.norm.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.1.norm.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.1.all_modules.0.weight: copying a param with shape torch.Size([320, 320, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([384, 384, 3, 3, 3]).
	size mismatch for decoder.stages.0.convs.1.all_modules.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.1.all_modules.1.weight: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.stages.0.convs.1.all_modules.1.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.transpconvs.0.weight: copying a param with shape torch.Size([320, 320, 1, 2, 2]) from checkpoint, the shape in current model is torch.Size([384, 384, 1, 2, 2]).
	size mismatch for decoder.transpconvs.0.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for decoder.transpconvs.1.weight: copying a param with shape torch.Size([320, 256, 2, 2, 2]) from checkpoint, the shape in current model is torch.Size([384, 256, 2, 2, 2]).
	size mismatch for decoder.seg_layers.0.weight: copying a param with shape torch.Size([1, 320, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 384, 1, 1, 1]).
```

</details>

## r20240531 (v2.5)

Release r20241024: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.5


```
sct_deepseg -install seg_sc_contrast_agnostic -custom-url https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.5/model_contrast-agnostic_20240930-1002.zip
```


```
sct_deepseg -i sub-zh04_ses-02_acq-sag_T2w.nii.gz -task seg_sc_contrast_agnostic

...

Using custom model from URL 'https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/v2.5/model_contrast-agnostic_20240930-1002.zip'.
...
```

```
mv sub-zh04_ses-02_acq-sag_T2w_seg.nii.gz sub-zh04_ses-02_acq-sag_T2w_seg_r20240531.nii.gz
```

## r20241113 (v2.6)

Release r20241024: https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/r20241113

```
sct_deepseg -install seg_sc_contrast_agnostic -custom-url https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/r20241113/model_contrast_agnostic_20241018-0508.zip
```

```
sct_deepseg -i sub-zh04_ses-02_acq-sag_T2w.nii.gz -task seg_sc_contrast_agnostic

...
Using custom model from URL 'https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/download/r20241113/model_contrast_agnostic_20241018-0508.zip'.
...
```

```
mv sub-zh04_ses-02_acq-sag_T2w_seg.nii.gz sub-zh04_ses-02_acq-sag_T2w_seg_r20241113.nii.gz
```


## SCIsegV2

For reference, I'm also trying `SCIsegV2` trained solely on SCI patients.

Release r20240729: https://github.com/ivadomed/model_seg_sci/releases/tag/r20240729

```
sct_deepseg -i sub-zh04_ses-02_acq-sag_T2w.nii.gz -task seg_sc_lesion_t2w_sci

...
Model 'model_seg_sci_multiclass_sc_lesion_nnunet' is up to date (Source: https://github.com/ivadomed/model_seg_sci/releases/download/r20240729/model_SCIsegV2_r20240729.zip)
...
```

```
mv sub-zh04_ses-02_acq-sag_T2w_sc_seg.nii.gz sub-zh04_ses-02_acq-sag_T2w_seg_SCIsegV2.nii.gz
```

## Results

Dropbox link with segmentation from different models: [link](https://www.dropbox.com/scl/fo/efbajr0vzt1uiuukyhogb/APnE2_RlZJVOdymrqkWSwzg?rlkey=jiaqdpid22mldg3f4ulnwv7qp&dl=1)

Command to open the segmentation:

```
fsleyes sub-zh04_ses-02_acq-sag_T2w.nii.gz -dr 0 1000 sub-zh04_ses-02_acq-sag_T2w_seg_r20240531.nii.gz -cm red sub-zh04_ses-02_acq-sag_T2w_seg_r20241113.nii.gz -cm green sub-zh04_ses-02_acq-sag_T2w_seg_SCIsegV2.nii.gz -cm blue
```

**Comment by valosekj** [comment]
The same comparison (`r20240531 (v2.5)` vs `r20241113 (v2.6)` vs `SCIsegV2 (r20240729)`) on a subject not used during training: `lumbar-marseille/sub-CTS10/ses-SPanat/anat/sub-CTS10_ses-SPanat_acq-ax_T2w.nii.gz`

Dropbox link with segmentation from different models: [link](https://www.dropbox.com/scl/fo/a4p9t9o5kuenkprtmia1g/ANgFKJH5tto-3lUdF32k5lQ?rlkey=t3qt3ijol92g5cpzdevo3vpcl&dl=1)

Command to open the segmentation:

```
fsleyes sub-CTS10_ses-SPanat_acq-ax_T2w.nii.gz  -dr 0 1000 sub-CTS10_ses-SPanat_acq-ax_T2w_seg_r20240531.nii.gz  -cm red sub-CTS10_ses-SPanat_acq-ax_T2w_seg_r20241113.nii.gz  -cm green sub-CTS10_ses-SPanat_acq-ax_T2w_seg_SCIsegV2.nii.gz -cm blue
```
